inputLocation: gs://sankir-storage-prospark/processed-retail-data/q1/2011-01-04.json
schemaLocation: gs://sankir-storage-prospark/input/t_transaction.json
ingressTable: retail_bq.t_transaction
errorTable: retail_bq.t_error
kpiLocation: gs://sankir-storage-prospark/kpi/kpiquery.json
tempKPIViewName: retail_tbl

cloudType: gcp
gcp:
  projectId: pro-Spark
  tempGCSBucket: sankir-storage-prospark
  serviceAccountPath: read_from_path

#aws:
#  kpi_table: abc
#  error_table: def

