runLocal: true
inputLocation: s3a://retail-sankir/processed-retail-data/q1/2011-01-04.json
schemaLocation: s3a://retail-sankir/schemas/retail_schema.json
businessValidatorClassName: com.sankir.smp.core.validators.RetailBusinessValidator
kpiLocation: s3a://retail-sankir/kpi/kpiquery.json
tempKPIViewName: "retail_tbl"
sparkConfig:
   fs.s3a.endpoint: "s3.us-east-2.amazonaws.com"

cloudType: aws
aws:
  tempAWSBucket: sankir-storage-prospark
  serviceAccountPath: read_from_path
  persistentStorage:
    type: object
    ingress: s3a://retail-sankir/ingress/
    error: s3a://retail-sankir/errors/
    kpi: s3a://retail-sankir/retail_kpi/
